#!/bin/bash
# This hook is sourced after every virtualenv is activated.

if [ "$color_prompt" = yes ]; then
    if [ -n "$VIRTUAL_ENV" ]; then
        PROMPT_COMMAND='__git_ps1 "${debian_chroot:+($debian_chroot)}(`basename $VIRTUAL_ENV`)\[\033[33m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]" "\\\$ "'
    else
        PROMPT_COMMAND='__git_ps1 "\[\033[33m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]" "\\\$ "'
    fi
else
    export PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
